cookie:
  expiry_days: 1
  key: knock_signature_key
  name: knock_cookie_name
credentials:
  usernames:
    demo:
      email: konyu@example.com
      name: demo
      password: $2b$12$oruu5wj2pheWLstSOe3IIua9K3JgoTNp.K7uq0cH9MKQj5eWaH/zS
